CONDITIONS = [
	"Light Drizzle",
	"Heavy Drizzle",
	"Drizzle",
	"Light Rain",
	"Heavy Rain",
	"Rain",
	"Light Snow",
	"Heavy Snow",
	"Snow",
	"Light Snow Grains",
	"Heavy Snow Grains",
	"Snow Grains",
	"Light Ice Crystals",
	"Heavy Ice Crytslas",
	"Ice Crystals",
	"Light Ice Pellets",
	"Heavy Ice Pellets",
	"Ice Pellets",
	"Light Hail",
	"Heavy Hail",
	"Hail",
	"Light Mist",
	"Heavy Mist",
	"Mist",
	"Light Low Drifting Snow",
	"Heavy Low Drifting Snow",
	"Low Drifting Snow",
	"Light Blowing Snow",
	"Heavy Blowing Snow",
	"Blowing Snow",
	"Light Rain Mist",
	"Heavy Rain Mist",
	"Rain Mist",
	"Light Rain Showers",
	"Heavy Rain Showers",
	"Rain Showers",
	"Light Snow Showers",
	"Heavy Snow Showers",
	"Snow Showers",
	"Light Snow Blowing Snow Mist",
	"Heavy Snow Blowing Snow Mist",
	"Snow Blowing Snow Mist",
	"Light Ice Pellet Showers",
	"Heavy Ice Pellet Showers",
	"Ice Pellet Showers",
	"Light Hail Showers",
	"Heavy Hail Showers",
	"Hail Showers",
	"Light Small Hail Showers",
	"Heavy Small Hail Showers",
	"Small Hail Showers",
	"Light Thunderstorm",
	"Heavy Thunderstorm",
	"Thunderstorm",
	"Light Thunderstorm and Rain",
	"Heavy Thunderstorm and Rain",
	"Thunderstorm and Rain",
	"Light Thunderstorm and Snow",
	"Heavy Thunderstorm and Snow",
	"Thunderstorm and Snow",
	"Light Thunderstorm and Ice Pellets",
	"Heavy Thunderstorm and Ice Pellets",
	"Thunderstorm and Ice Pellets",
	"Light Thunderstorm with Hail",
	"Heavy Thunderstorm with Hail",
	"Thunderstorm with Hail",
	"Light Thunderstorm with Small Hail",
	"Heavy Thunderstorm with Small Hail",
	"Thunderstorm with Small Hail",
	"Light Freezing Drizzle",
	"Heavy Freezing Drizzle",
	"Freezing Drizzle",
	"Light Freezing Rain",
	"Heavy Freezing Rain",
	"Freezing Rain",
	"Small Hail",
	"Squalls",
	"Funnel Cloud",
	"Unknown Precipitation",
	"Chance of Flurries",
	"Chance of Rain",
	"Chance Rain",
	"Chance of Freezing Rain",
	"Chance of Sleet",
	"Chance of Snow",
	"Chance of Thunderstorms",
	"Chance of a Thunderstorm",
	"Flurries",
	"Sleet",
	"Chance of Showers",
	"Showers",
	"Chance of Snow Showers",
	"Chance of Ice Pellets",
	"Blizzard"
]
