# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAlert_app', '0002_auto_20170518_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='USA', max_length=64),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
