# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-16 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherAlert_app', '0003_auto_20170518_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
